"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { StyledEngineProvider } from '@mui/material/styles';
import { appStore } from './store/appStore';
import { Provider } from 'react-redux';



const inter = Inter({ subsets: ['latin'] })

//export const metadata = {
  //title: 'Create Next App',
  //description: 'Generated by create next app',
//}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
    rel="stylesheet"
     href="https://fonts.googleapis.com/icon?family=Material+Icons"
      />

      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider store={appStore}>
          <StyledEngineProvider>
        {children}
        </StyledEngineProvider>
        </Provider>
        </body>
    </html>
  )
}
